version: '2'

services:
  controller:
    image: ansible-controller
    depends_on:
      - loadbalancer
      - app01
      - app02
      - database
    volumes:
      - ./init-scripts:/usr/src/app/init-scripts
      - ./playbooks:/ansible/playbooks
    entrypoint: /usr/src/app/init-scripts/init.sh
    restart: unless-stopped
  loadbalancer:
    image: ansible-node
    restart: always
  app01:
    image: ansible-node
    restart: always
  app02:
    image: ansible-node
    restart: always
  database:
    image: ansible-node
    restart: always

networks:
  custom:
    driver: bridge